# Netlify configuration

[build]
  # Directory with code to build
  base = "client"
  # Command to run to build the site
  command = "npm run build"
  # Directory to deploy
  publish = "dist"
  # Functions directory
  functions = "netlify/functions"

# For single page applications - redirect all requests to index.html
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Environment variables configuration
[context.production.environment]
  VITE_API_URL = "/.netlify/functions"

[context.branch-deploy.environment]
  VITE_API_URL = "/.netlify/functions"

[context.deploy-preview.environment]
  VITE_API_URL = "/.netlify/functions" 